/**
	Generated by sails-inverse-model
	Date:Sun Oct 27 2019 18:40:45 GMT-0400 (-04)
*/

module.exports = {
    attributes: {
        createdAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        },
        updatedAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        },
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        identificacion: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        nombre: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        img: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        paterno: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        materno: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        telefono: {
            type: "number",
            columnType: "double"
        },
        celular: {
            type: "number",
            columnType: "double"
        },
        cedula: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        expedido: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        fechaNacimiento: {
            type: "string",
            columnType: "date"
        },
        sexo: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        rol: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        }
    }
};