/**
	Generated by sails-inverse-model
	Date:Sun Oct 27 2019 18:40:44 GMT-0400 (-04)
*/

module.exports = {
    attributes: {
        createdAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        },
        updatedAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        },
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        lugar: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        peso: {
            type: "number",
            columnType: "double"
        },
        estatura: {
            type: "number",
            columnType: "double"
        },
        cabeza: {
            type: "number",
            columnType: "double"
        },
        fecha: {
            type: "string",
            columnType: "date"
        },
        idPaciente: {
            type: "number",
            columnType: "int",
            isInteger: true
        }
    }
};