/**
	Generated by sails-inverse-model
	Date:Sun Oct 27 2019 18:40:45 GMT-0400 (-04)
*/

module.exports = {
    attributes: {
        createdAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        },
        updatedAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        },
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        username: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        password: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        rol: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        idPersona: {
            type: "number",
            columnType: "int",
            isInteger: true,
            unique: true
        }
    }
};